version: '3.3'
services:
    web:
        build:
            dockerfile: nginx/Dockerfile
            args:
            - UID=${UID:-1000}
            - GID=${GID:-1000}
        container_name: nginx_container
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./project:/var/www/html:delegated
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            #- db
    php:
        build:
            dockerfile: php/Dockerfile
            args:
              - UID=${UID:-1000}
              - GID=${GID:-1000}
        container_name: php_container
        restart: always
          
        volumes:
           # - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
           # - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./project:/var/www/html:delegated
